routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard/getdatacompletenotpaid', ['uses' => 'HomeController@get_data_complete_not_paid', 'as' => 'dashboard.getdatacompletenotpaid']);
Route::get('/dashboard/ordersdate', ['uses' => 'HomeController@get_orders_date', 'as' => 'dashboard.getordersdate']);
Route::get('/dashboard/gettotalprice', ['uses' => 'HomeController@get_total_price', 'as' => 'dashboard.gettotalprice']);
Route::get('/dashboard/ordersclassification', ['uses' => 'HomeController@get_orders_classification', 'as' => 'dashboard.getordersclassification']);
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');

/* ---------- Master ---------- */

Route::get('/customer/getdata', ['uses' => 'Master\CustomerController@get_data', 'as' => 'customer.getdata']);
Route::resource('/customer', 'Master\CustomerController');

Route::get('/postalCode/getdata', ['uses' => 'Master\PostalCodeController@get_data', 'as' => 'postalCode.getdata']);
Route::post('/postalCode/getdataforselect', ['uses' => 'Master\PostalCodeController@get_data_for_select', 'as' => 'postalCode.getdataforselect']);
Route::resource('/postalCode', 'Master\PostalCodeController');

Route::get('/courier/getdata', ['uses' => 'Master\CourierController@get_data', 'as' => 'courier.getdata']);
Route::resource('/courier', 'Master\CourierController');

Route::get('/orderStatus/getdata', ['uses' => 'Master\OrderStatusController@get_data', 'as' => 'orderStatus.getdata']);
Route::resource('/orderStatus', 'Master\OrderStatusController');

Route::get('/restaurant/getdata', ['uses' => 'Master\RestaurantController@get_data', 'as' => 'restaurant.getdata']);
Route::resource('/restaurant', 'Master\RestaurantController');

Route::get('/menu/gethalal', ['uses' => 'Master\MenuController@get_halal', 'as' => 'menu.get_halal']);
Route::get('/menu/idxhalal', ['uses' => 'Master\MenuController@idx_halal', 'as' => 'menu.idx_halal']);
Route::get('/menu/getrelease', ['uses' => 'Master\MenuController@get_release', 'as' => 'menu.get_release']);
Route::get('/menu/idxrelease', ['uses' => 'Master\MenuController@idx_release', 'as' => 'menu.idx_release']);
Route::post('/menu/getdatabyid', ['uses' => 'Master\MenuController@get_data_by_id', 'as' => 'menu.getdatabyid']);
Route::post('/menu/getdataforselect', ['uses' => 'Master\MenuController@get_data_for_select', 'as' => 'menu.getdataforselect']);
Route::get('/menu/getdata', ['uses' => 'Master\MenuController@get_data', 'as' => 'menu.getdata']);
Route::resource('/menu', 'Master\MenuController');

Route::get('/categoryType/getdata', ['uses' => 'Master\CategoryTypeController@get_data', 'as' => 'categoryType.getdata']);
Route::resource('/categoryType', 'Master\CategoryTypeController');

Route::get('/category/getdata', ['uses' => 'Master\CategoryController@get_data', 'as' => 'category.getdata']);
Route::resource('/category', 'Master\CategoryController');

Route::get('/promo/getdata', ['uses' => 'Master\PromoController@get_data', 'as' => 'promo.getdata']);
Route::resource('/promo', 'Master\PromoController');



/* ---------- Order ---------- */

Route::get('/order/getdatapaid', ['uses' => 'Order\OrderController@get_data_paid', 'as' => 'order.getdatapaid']);
Route::post('/order/getinvoice', ['uses' => 'Order\OrderController@get_invoice', 'as' => 'order.getinvoice']);
Route::get('/order/getdata', ['uses' => 'Order\OrderController@get_data', 'as' => 'order.getdata']);
Route::resource('/order', 'Order\OrderController');

Route::post('/orderDetail/getdatabycustomerorderid', ['uses' => 'order\OrderDetailController@get_data_by_customer_order_id', 'as' => 'orderDetail.getdatabycustomerorder']);
Route::resource('/orderDetail', 'Order\OrderDetailController');

Route::get('/customerPoint/getdata', ['uses' => 'order\CustomerPointController@get_data', 'as' => 'customerPoint.getdata']);
Route::resource('/customerPoint', 'Order\CustomerPointController');

/* ---------- Sales ---------- */

Route::get('/transactions/getdata', ['uses' => 'Finance\TransactionsController@get_data', 'as' => 'transactions.getdata']);
Route::resource('/transactions', 'Finance\TransactionsController');


Route::get('/reportSales/getnetpermonth', ['uses' => 'Sales\ReportController@get_net_per_month', 'as' => 'reportSales.getnetpermonth']);
Route::get('/reportSales/getgrosspermonth', ['uses' => 'Sales\ReportController@get_gross_per_month', 'as' => 'reportSales.getgrosspermonth']);
Route::get('/reportSales/getadspermonth', ['uses' => 'Sales\ReportController@get_ads_per_month', 'as' => 'reportSales.getadspermonth']);
Route::get('/reportSales/getexpensespermonth', ['uses' => 'Sales\ReportController@get_expenses_per_month', 'as' => 'reportSales.getexpensespermonth']);
Route::get('/reportSales/getcustomerpermonth', ['uses' => 'Sales\ReportController@get_customer_per_month', 'as' => 'reportSales.getcustomerpermonth']);
Route::get('/reportSales/getprofitpermonth', ['uses' => 'Sales\ReportController@get_profit_per_month', 'as' => 'reportSales.getprofitpermonth']);
Route::post('/reportSales/getreport', ['uses' => 'Sales\ReportController@get_report', 'as' => 'reportSales.getreport']);
Route::post('/reportSales/getcustomer', ['uses' => 'Sales\ReportController@get_total_customer', 'as' => 'reportSales.getcustomer']);
Route::get('/reportSales/getdata', ['uses' => 'Sales\ReportController@get_data', 'as' => 'reportSales.getdata']);
Route::resource('/reportSales', 'Sales\ReportController');

resources/views/template/error.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
  {{ $message }}
</div>
@endif


@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
  {{ $message }}
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	{{ $message }}
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	{{ $message }}
</div>
@endif


@if ($errors->any())
  <div class="alert alert-danger alert-block mb-4">
    <button type="button" class="close" data-dismiss="alert">×</button>	
    <ul class="mb-0">
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

resources/views/template/footer.blade.php
<div class="footer-wrapper">
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-center text-sm-left d-block d-sm-inline-block">Copyright &copy; 2019. All rights reserved.</span> <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Kangen Makanan Bali</span>
        </div>
    </footer>
</div>

resources/views/template/main.blade.php
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Kangen Makanan Bali</title>
    <meta name="description" content="Kangen Makanan Bali">
    <meta name="author" content="Kangen Makanan Bali">

    <link rel="stylesheet" type="text/css" href="{{ asset('/css/app.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.materialdesignicons.com/4.5.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('/vendors/base/vendor.bundle.base.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/css/vertical-layout-light/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/css/custom.css') }}">
    <link type="text/css" href="{{asset('/vendors/bootstrap-sweetalert/dist/sweetalert.css')}}" rel="stylesheet">
    <script src="{{asset('/vendors/bootstrap-sweetalert/dist/sweetalert.min.js')}}"></script>

    @yield('css-content')
    <script>
        function generateNotification($alert_type, $message) {
            var html = '<div class="alert alert-' + $alert_type + '"><button type="button" class="close" data-dismiss="alert">&times;</button>';
            html += '<p>' + $message + '</p>';
            html += '</div>';

            return $.parseHTML(html);
        }
    </script>
    @php
    $page = "";
    @endphp

</head>

<body>

    <div class="overlay">
        <img src="{{ asset('/img/loading.gif') }}" alt="loading"/>
    </div>

    <div class="container-scroller">
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-left navbar-brand-wrapper d-flex align-items-center justify-content-between">
                <a class="navbar-brand brand-logo" href="#">
                    KMB
                </a>                 
                <a class="navbar-brand brand-logo-mini" href="">
                <img src="{{ asset('/img/mp-mini.png') }}" alt="logo"/>
                </a> 
                <button class="navbar-toggler align-self-center" data-toggle="minimize" type="button">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item  dropdown d-none align-items-center d-lg-flex d-none">
                        <p class="mb-0">{{ \Carbon\Carbon::now()->format('d F Y') }}</p>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item  dropdown d-none align-items-center d-lg-flex d-none">
                        <a class="dropdown-toggle btn btn-outline-secondary btn-fw"  href="#" data-toggle="dropdown" id="pagesDropdown">                        
                            <span class="nav-profile-name"></span>         
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="pagesDropdown">
                            <div class="text-center my-3">
                                
                                <p class="dropdown-header mt-3"><strong><span class=""></span></strong></p>
                                <p class=""><span class=""></span></p>
                            </div>
                            <a class="dropdown-item" href="">
                            <i class="mdi mdi-lock-open text-primary"></i>
                            Change Password
                            </a>
                            <a class="dropdown-item" href="">
                            <i class="mdi mdi-key text-primary"></i>
                            Change PIN
                            </a>
                            <a class="dropdown-item" href="" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="mdi mdi-logout text-primary"></i>
                            Logout
                            </a>
                            <form id="logout-form" action="" method="POST" style="display:none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>

        <div class="container-fluid page-body-wrapper">
        
        @include('template.sidebar')
        <!-- END Navbar -->

            <!-- START Main Panel -->
            <div class="main-panel">
                <!-- START Content -->
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-md-12">
                            @yield('main-content')
                        </div>
                    </div>
                </div>
                <!-- END Content -->

                <!-- START Footer -->
                @include('template.footer')
                <!-- END Footer -->

            </div>
            <!-- END Main Panel -->
        
        </div>
    </div>

    <script type="text/javascript" src="{{ asset('/vendors/base/vendor.bundle.base.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/js/template.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/js/off-canvas.js') }}"></script>

    <!-- Custom js for this page-->
    @yield('js-content')
    <!-- End custom js for this page-->

</body>
</html>

resources/views/template/select.blade.php
@foreach ($models as $m)
  <option value="{{ $m->id }}">{{ $m->name }}</option>
@endforeach 

resources/views/template/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{{ route('home') }}"><i class="mdi mdi-shield-check menu-icon"></i> <span class="menu-title">Dashboard</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('order.index') }}"><i class="mdi mdi-file-document-box-check-outline menu-icon"></i> <span class="menu-title">Order</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('customer.index') }}"><i class="mdi mdi-account-edit menu-icon"></i> <span class="menu-title">Customer</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('customerPoint.index') }}"><i class="mdi mdi-account-edit menu-icon"></i> <span class="menu-title">Point</span></a>
      </li>
      <li class="nav-item">
        <a aria-controls="ui-basic" aria-expanded="false" class="nav-link" data-toggle="collapse" href="#sales">
            <i class="mdi mdi-account-settings menu-icon"></i> <span class="menu-title">Sales</span> <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="sales">
            <ul class="nav flex-column sub-menu">
              <li class="nav-item">
                <a class="nav-link" href="{{ route('transactions.index') }}">Transactions</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('reportSales.index') }}">Report</a>
                </li>
            </ul>
        </div>
      </li>
      
      <li class="nav-item">
        <a aria-controls="ui-basic" aria-expanded="false" class="nav-link" data-toggle="collapse" href="#master">
            <i class="mdi mdi-account-settings menu-icon"></i> <span class="menu-title">Master</span> <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="master">
            <ul class="nav flex-column sub-menu">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('category.index') }}">Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('categoryType.index') }}">Category Type</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('courier.index') }}">Courier</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('menu.index') }}">Menu</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('orderStatus.index') }}">Order Status</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('postalCode.index') }}">Postal Code</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('promo.index') }}">Promo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('restaurant.index') }}">Restaurant</a>
                </li>
                
            </ul>
        </div>
      </li>
         
  </ul>
</nav>