routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard/getdatacompletenotpaid', ['uses' => 'HomeController@get_data_complete_not_paid', 'as' => 'dashboard.getdatacompletenotpaid']);
Route::get('/dashboard/ordersdate', ['uses' => 'HomeController@get_orders_date', 'as' => 'dashboard.getordersdate']);
Route::get('/dashboard/gettotalprice', ['uses' => 'HomeController@get_total_price', 'as' => 'dashboard.gettotalprice']);
Route::get('/dashboard/ordersclassification', ['uses' => 'HomeController@get_orders_classification', 'as' => 'dashboard.getordersclassification']);
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');

/* ---------- Master ---------- */

Route::get('/customer/getdata', ['uses' => 'Master\CustomerController@get_data', 'as' => 'customer.getdata']);
Route::resource('/customer', 'Master\CustomerController');

Route::get('/postalCode/getdata', ['uses' => 'Master\PostalCodeController@get_data', 'as' => 'postalCode.getdata']);
Route::post('/postalCode/getdataforselect', ['uses' => 'Master\PostalCodeController@get_data_for_select', 'as' => 'postalCode.getdataforselect']);
Route::resource('/postalCode', 'Master\PostalCodeController');

Route::get('/courier/getdata', ['uses' => 'Master\CourierController@get_data', 'as' => 'courier.getdata']);
Route::resource('/courier', 'Master\CourierController');

Route::get('/orderStatus/getdata', ['uses' => 'Master\OrderStatusController@get_data', 'as' => 'orderStatus.getdata']);
Route::resource('/orderStatus', 'Master\OrderStatusController');

Route::get('/restaurant/getdata', ['uses' => 'Master\RestaurantController@get_data', 'as' => 'restaurant.getdata']);
Route::resource('/restaurant', 'Master\RestaurantController');

Route::get('/menu/gethalal', ['uses' => 'Master\MenuController@get_halal', 'as' => 'menu.get_halal']);
Route::get('/menu/idxhalal', ['uses' => 'Master\MenuController@idx_halal', 'as' => 'menu.idx_halal']);
Route::get('/menu/getrelease', ['uses' => 'Master\MenuController@get_release', 'as' => 'menu.get_release']);
Route::get('/menu/idxrelease', ['uses' => 'Master\MenuController@idx_release', 'as' => 'menu.idx_release']);
Route::post('/menu/getdatabyid', ['uses' => 'Master\MenuController@get_data_by_id', 'as' => 'menu.getdatabyid']);
Route::post('/menu/getdataforselect', ['uses' => 'Master\MenuController@get_data_for_select', 'as' => 'menu.getdataforselect']);
Route::get('/menu/getdata', ['uses' => 'Master\MenuController@get_data', 'as' => 'menu.getdata']);
Route::resource('/menu', 'Master\MenuController');

Route::get('/categoryType/getdata', ['uses' => 'Master\CategoryTypeController@get_data', 'as' => 'categoryType.getdata']);
Route::resource('/categoryType', 'Master\CategoryTypeController');

Route::get('/category/getdata', ['uses' => 'Master\CategoryController@get_data', 'as' => 'category.getdata']);
Route::resource('/category', 'Master\CategoryController');

Route::get('/promo/getdata', ['uses' => 'Master\PromoController@get_data', 'as' => 'promo.getdata']);
Route::resource('/promo', 'Master\PromoController');



/* ---------- Order ---------- */

Route::get('/order/getdatapaid', ['uses' => 'Order\OrderController@get_data_paid', 'as' => 'order.getdatapaid']);
Route::post('/order/getinvoice', ['uses' => 'Order\OrderController@get_invoice', 'as' => 'order.getinvoice']);
Route::get('/order/getdata', ['uses' => 'Order\OrderController@get_data', 'as' => 'order.getdata']);
Route::resource('/order', 'Order\OrderController');

Route::post('/orderDetail/getdatabycustomerorderid', ['uses' => 'order\OrderDetailController@get_data_by_customer_order_id', 'as' => 'orderDetail.getdatabycustomerorder']);
Route::resource('/orderDetail', 'Order\OrderDetailController');

Route::get('/customerPoint/getdata', ['uses' => 'order\CustomerPointController@get_data', 'as' => 'customerPoint.getdata']);
Route::resource('/customerPoint', 'Order\CustomerPointController');

/* ---------- Sales ---------- */

Route::get('/transactions/getdata', ['uses' => 'Finance\TransactionsController@get_data', 'as' => 'transactions.getdata']);
Route::resource('/transactions', 'Finance\TransactionsController');


Route::get('/reportSales/getnetpermonth', ['uses' => 'Sales\ReportController@get_net_per_month', 'as' => 'reportSales.getnetpermonth']);
Route::get('/reportSales/getgrosspermonth', ['uses' => 'Sales\ReportController@get_gross_per_month', 'as' => 'reportSales.getgrosspermonth']);
Route::get('/reportSales/getadspermonth', ['uses' => 'Sales\ReportController@get_ads_per_month', 'as' => 'reportSales.getadspermonth']);
Route::get('/reportSales/getexpensespermonth', ['uses' => 'Sales\ReportController@get_expenses_per_month', 'as' => 'reportSales.getexpensespermonth']);
Route::get('/reportSales/getcustomerpermonth', ['uses' => 'Sales\ReportController@get_customer_per_month', 'as' => 'reportSales.getcustomerpermonth']);
Route::get('/reportSales/getprofitpermonth', ['uses' => 'Sales\ReportController@get_profit_per_month', 'as' => 'reportSales.getprofitpermonth']);
Route::post('/reportSales/getreport', ['uses' => 'Sales\ReportController@get_report', 'as' => 'reportSales.getreport']);
Route::post('/reportSales/getcustomer', ['uses' => 'Sales\ReportController@get_total_customer', 'as' => 'reportSales.getcustomer']);
Route::get('/reportSales/getdata', ['uses' => 'Sales\ReportController@get_data', 'as' => 'reportSales.getdata']);
Route::resource('/reportSales', 'Sales\ReportController');

app/Models/Master/CategoryType.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class CategoryType extends Model
{
    protected $table = 'm_category_type';
    
    protected $fillable = [
        'name',
        'note',
        'status',
        'is_expenses'
    ];
}

app/Http/Controllers/Master/CategoryController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Models\Master\Category;
use App\Models\Master\CategoryType;
use Carbon\Carbon;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view( 'master.category.index' );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category       = new Category();
        $categoryType   = CategoryType::select('id', 'name')->where('status', 1)->get();

        return view( 
            'master.category.form', 
            [
                'category'         => $category, 
                'categoryType'    => $categoryType,
            ] 
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => ['required', 'min:3', 'max:100']
        ]);

        $model = Category::create(
            [
                'id_m_category_type'    => $request->categoryType,
                'name'                  => $request->name,
                'note'                  => $request->note, 
                'status'                => (isset( $request->status ) ? 1 : 0)
            ]
        );
        
        return redirect( '/category' );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Master\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Master\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view( 'master.category.form', compact('category') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Master\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        request()->validate([
            'name' => ['required', 'min:3', 'max:100']
        ]);

        $model = Category::find($category->id);  

        if ($model) {
            $this->old_data = $this->serialize_data($model);

            $model->name                = $request->name;
            $model->id_m_category_type  = $request->categoryType;
            $model->note                = $request->note; 
            $model->status              = 1;

            $model->save();     

        }
        
        return redirect( route('category.index') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Master\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Category $category)
    {
        $model = Category::find($category->id);

        if ($model) {
            $this->old_data = $this->serialize_data($model);
                
            $model->status      = 0;
            $model->deleted_at  = Carbon::now();
            $model->deleted_by  = auth()->user()->username;  

            $model->save();  

        }       

        return response()->json(true);
    }

    /**
     * Generate json listing of the resource for datatable.
     *
     * @return \Illuminate\Http\Response
     */
    public function get_data()
    {
        $models =   Category::select('id', 'id_m_category_type', 'name', 'note')
                    ->where([
                        ['status', 1],
                    ])
                    ->with('category_type')
                    ->get();

        $data = [
            'data' => $models
        ];

        return response()->json($data);
    }
}

app/Http/Controllers/Master/CategoryTypeController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Models\Master\CategoryType;
use Illuminate\Http\Request;
use Carbon\Carbon;

class CategoryTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view( 'master.category_type.index' );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $categoryType = new CategoryType();
        return view( 'master.category_type.form', compact('categoryType') );
    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => ['required', 'min:3', 'max:100']
        ]);

        $model = CategoryType::create(
            [
                'name'          => $request->name,
                'note'          => $request->note, 
                'is_expenses'   => $request->is_expenses, 
                'status' => (isset( $request->status ) ? 1 : 0)
            ]
        );
        
        return redirect( '/categoryType' );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Master\CategoryType  $categoryType
     * @return \Illuminate\Http\Response
     */
    public function show(CategoryType $categoryType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Master\CategoryType  $categoryType
     * @return \Illuminate\Http\Response
     */
    public function edit(CategoryType $categoryType)
    {
        return view( 'master.category_type.form', compact('categoryType') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Master\CategoryType  $categoryType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CategoryType $categoryType)
    {
        request()->validate([
            'name' => ['required', 'min:3', 'max:100']
        ]);

        $model = CategoryType::find($categoryType->id);  

        if ($model) {
                
            $model->name        = $request->name;
            $model->note        = $request->note; 
            $model->is_expenses = (isset( $request->is_expenses ) ? 1 : 0); 
            
            $model->status      = 1;

            $model->save();     

        }
        
        return redirect( route('categoryType.index') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Master\CategoryType  $categoryType
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, CategoryType $categoryType)
    {
        $model = CategoryType::find($categoryType->id);

        if ($model) {
                
            $model->status      = 0;
            $model->deleted_at  = Carbon::now();
            $model->deleted_by  = "Natasia";  

            $model->save();  

        }       

        return response()->json(true);
    }

    /**
     * Generate json listing of the resource for datatable.
     *
     * @return \Illuminate\Http\Response
     */
    public function get_data()
    {
        $models =   CategoryType::select('id', 'name', 'note', 'is_expenses')
                    ->where([
                        ['status', 1],
                    ])
                    ->get();

        $data = [
            'data' => $models
        ];

        return response()->json($data);
    }
}

app/Http/Controllers/Master/CourierController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Models\Master\Courier;
use Illuminate\Http\Request;

class CourierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view( 'master.courier.index' );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courier = new Courier();
        return view( 'master.courier.form', compact('courier') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => ['required', 'min:3', 'max:100']
        ]);

        $model = Courier::create(
            [
                'name' => $request->name,
                'note' => $request->note, 
                'status' => (isset( $request->status ) ? 1 : 0)
            ]
        );
        
        return redirect( '/courier' );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Master\Courier  $courier
     * @return \Illuminate\Http\Response
     */
    public function show(Courier $courier)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Master\Courier  $courier
     * @return \Illuminate\Http\Response
     */
    public function edit(Courier $courier)
    {
        return view( 'master.courier.form', compact('courier') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Master\Courier  $courier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Courier $courier)
    {
        request()->validate([
            'name' => ['required', 'min:3', 'max:100']
        ]);

        $model = Courier::find($courier->id);  

        if ($model) {
            $this->old_data = $this->serialize_data($model);
                
            $model->name        = $request->name;
            $model->note        = $request->note; 
            $model->status      = 1;

            $model->save();     

        }
        
        return redirect( route('courier.index') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Master\Courier  $courier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Courier $courier)
    {
        $model = Country::find($country->id);

        if ($model) {
            $this->old_data = $this->serialize_data($model);
                
            $model->status      = 0;
            $model->deleted_at  = Carbon::now();
            $model->deleted_by  = auth()->user()->username;  

            $model->save();  

        }       

        return response()->json(true);
    }

    /**
     * Generate json listing of the resource for datatable.
     *
     * @return \Illuminate\Http\Response
     */
    public function get_data()
    {
        $models =   Courier::select('id', 'name', 'note')
                    ->where([
                        ['id', '!=', 0],
                        ['status', 1],
                    ])
                    ->get();

        $data = [
            'data' => $models
        ];

        return response()->json($data);
    }
}

resources/views/master/promo/form.blade.php
@extends('template.main')
@section('main-content')
<div class="row">
  <div class="col-lg-12 d-flex flex-column grid-margin stretch-card">
   <div class="card bg-dark">
      <div class="card-body">
        <h4 class="display-4 pb-0 mb-0 text-white">Promo</h4>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-6 col-md-12 d-flex flex-column">
  
  @include('template.error')
  
    <div class="card">
      <div class="card-body">
        
        <form class="mpform" id="mpform" method="POST" action="@if( isset($promo->id) ){{ route('promo.update', ['promo' => $promo->id]) }}@else{{ route('promo.store') }}@endif">
          @if( isset($promo->id) ) {{ method_field('PATCH') }} @else {{ method_field('POST') }} @endif          
          @csrf
          <input type="hidden" id="id" name="id" value="{{ $promo->id }}">
          <fieldset class="form-group">
            <div class="row">
              <legend class="col-form-label col-sm-3 pt-0">Status</legend>
              <div class="col-sm-9">
                <div class="form-check form-check-inline">
                  <label for="status" class="form-check-label">
                  <input type="checkbox" class="form-check-input" id="status" name="status" 
                      @if( isset($promo->id) ) @if( $promo->status == 1 ) checked @else unchecked @endif @else checked @endif
                    />
                    Status
                  <i class="input-helper"></i></label>
                </div>
              </div>
            </div>
          </fieldset> 
          <div class="form-group row">
            <label for="name" class="col-sm-3 col-form-label">Name</label>
            <div class="col-sm-9">
              <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" id="name" name="name" placeholder="Name" value="{{ $errors->has('name') ? old('name' ) : $promo->name }}">
            </div>
          </div>
          <div class="form-group row">
            <label for="price" class="col-sm-3 col-form-label">Price</label>
            <div class="col-sm-9">
              <input type="text" class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" id="price" name="price" placeholder="Price" value="{{ $errors->has('price') ? old('price' ) : $promo->price }}">
            </div>
          </div>
          <div class="form-group row">
            <label for="note" class="col-sm-3 col-form-label">Description</label>
            <div class="col-sm-9">
              <textarea name="note" id="note" class="simpleMde">{!! $promo->note !!}</textarea>
            </div>
          </div>  
          
          <div class="form-group mt-5 float-right">             
            <a href="{{ route('promo.index') }}"><button type="button" class="btn btn-lg btn-light mr-3" id="cancel" name="cancel">Cancel</button></a>
            <button type="submit" class="btn btn-lg btn-primary">Save</button>
          </div>
        </form>

      </div>
    </div>
  </div>
</div>
@endsection

@section('css-content')
<link rel="stylesheet" type="text/css" href="{{ asset('/vendors/simplemde/simplemde.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('/css/custom.css') }}">
@endsection

@section('js-content')
<script type="text/javascript" src="{{ asset('/vendors/simplemde/simplemde.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/js/general/editor.js') }}"></script>
@endsection

resources/views/master/promo/index.blade.php
@extends('template.main')
@section('main-content')
<meta name="_token" content="{{ csrf_token() }}">
<div class="row">
  <div class="col-lg-12 d-flex flex-column grid-margin stretch-card">
   <div class="card bg-dark">
      <div class="card-body">
        <h4 class="display-4 pb-0 mb-0 text-white">Promo</h4>
      </div>
    </div>
  </div>
</div>

@include('template.error')

<div class="row">
  <div class="col-lg-12 col-md-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">   
        <p>
          <a href="{{ route('promo.create') }}">
            <button class="btn btn-lg btn-primary mb-3" id="delete" name="delete">Create New</button>
          </a>
        </p>
        <div class="row">
          <div class="col-12">
            <div class="table-responsive-lg">
              <table id="table-listing" class="table table-bordered table-hover">
                <thead class="thead-dark">
                  <tr>
                    <th>&nbsp;</th> 
                    <th>Name</th>
                    <th>Price</th>
                    <th>Note</th>
                    <th>&nbsp;</th>
                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('css-content')
<link rel="stylesheet" type="text/css" href="{{ asset('/vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}">
@endsection

@section('js-content')
<script type="text/javascript" src="{{ asset('/vendors/datatables.net/jquery.dataTables.js') }}"></script>
<script type="text/javascript" src="{{ asset('/vendors/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
<script type="text/javascript">
  var url_base      = "{{ route('promo.index') }}";  
  var data_route    = "{{ route('promo.getdata') }}";
</script>
<script type="text/javascript">
$(document).ready(function() {

  function formatNumber(num) {
    return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')
  }

  var t = $('#table-listing').DataTable({
      lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
      dom: 'Bfrtip',
      buttons: [
          'pageLength', 
          {
            extend: 'copy',
            exportOptions: { 
              columns: [ 0, 1, 2 ], 
              rows: ':visible' 
            }
          },
          {
            extend: 'csv',
            exportOptions: { 
              columns: [ 0, 1, 2 ], 
              rows: ':visible' 
            }
          },
          {
            extend: 'excel',
            exportOptions: { 
              columns: [ 0, 1, 2 ], 
              rows: ':visible' 
            }
          },
          {
            extend: 'pdf',
            exportOptions: { 
              columns: [ 0, 1, 2 ], 
              rows: ':visible' 
            },
            customize: function (doc) {
              doc.content[1].table.widths = 
                  Array(doc.content[1].table.body[0].length + 1).join('*').split('');
            }
          },
          {
            extend: 'print',
            exportOptions: { 
              columns: [ 0, 1, 2 ], 
              rows: ':visible' 
            }
          }
      ],
      ordering: true,
      order: [1, 'asc'],
      pageLength: 50,
      ajax: {
          type: "GET",
          url: data_route,
          dataType: "json",
          'error': function (xhr, textStatus, ThrownException) {
            console.log(ThrownException);
            // alert('Error loading data. Exception: ' + ThrownException + "\n" + textStatus);
          }
      },
      columns: [
        {
          data: "id", 
          defaultContent: '',
          searchable: false,
          orderable: false,
        },
        { data: "name" },
        {
          data: 'price',
          render: function(data, type, row) {
            if(data != null){
              return "Rp "+ formatNumber(data);
            }else{
              return "";
            }
            
          }
        },
        { data: "note" },
        {
          data: 'id',
          render: function(data, type, row) {
            var string_button = "";
           
            string_button += '<a href="' + url_base + "/" + data + '/edit" class="text-primary mr-1 p-2"><i class="mdi mdi-lead-pencil"></i></a>';
            string_button += '<a href="" onclick="showSwal(' + data + ')" class="text-danger mr-1 p-2"><i class="mdi mdi-delete"></i></a>';
            return string_button;
          },
          orderable: false
        }
      ]
    });

    t.on( 'order.dt search.dt', function () {
      t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
          cell.innerHTML = i+1;
          t.cell(cell).invalidate('dom');
      } );
    }).draw();

    $.ajaxSetup({
      headers: {
        'X-CSRF-Token': $('meta[name="_token"]').attr('content')
      }
    });
    
    showSwal = function(item_id) {
      event.preventDefault();

      swal({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        buttons: {
          cancel: {
            text: "Cancel",
            value: null,
            visible: true,
            closeModal: true,
          },
          confirm: {
            text: "OK",
            value: true,
            visible: true,
            closeModal: true,
          }
        }
      }).then((result) => {
        if (result) {
          var token = $('[name="_token"]').val();
          $.post(url_base + '/' + item_id, {"_method" : "DELETE", "_token" : token}, function(response) {
            if (response == true) {
              swal({
                title: 'Deleted!',
                text: 'Item has been deleted.',
                icon: 'success'
              }).then((result) => {
                window.location.reload();
              });    
            } else {
              swal({
                title: 'Delete failed!',
                text: 'Item is not deleted.',
                icon: 'error'
              })
            }
            
          });
        } 
      })
    };

});
</script>
@endsection